/// This module contains all the autogenerated abigen! contract bindings
pub mod arbitrage_swap;
pub mod context;
pub mod erc20;
pub mod flash_bots_uniswap_query;
pub mod i_uniswap_v2_factory;
pub mod i_uniswap_v2_pair;
pub mod ierc20;
pub mod ierc20_metadata;
pub mod iweth9;
pub mod t_token;
pub mod weth9;
