/// This module contains all the autogenerated abigen! contract bindings
pub mod context;
pub mod ds_test;
pub mod erc20;
pub mod i_uniswap_v2_pair;
pub mod ierc20;
pub mod ierc20_metadata;
pub mod test_wrapper;
pub mod wrapper;